config/routes.rb
ImgurClone::Application.routes.draw do
  resources :users, only: [:new, :create, :show, :update]
  resource :session, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit]

  resources :images do
    resources :comments, only: [:new, :create]
    member do
      post "upvote"
      post "downvote"
    end
  end

  match "/comments/:id/upvote" => "comments#upvote", as: :upvote_comment
  match "/comments/:id/downvote" => "comments#downvote", as: :downvote_comment

  root to: 'images#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_digest, :password, :password_confirmation

  has_secure_password

  before_save { self.email = self.email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
    presence: true,
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }

  has_many :sessions, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :albums
  has_many :comments
  has_many :user_comment_votes
  has_many :user_image_votes
  has_many :password_resets

  def send_password_reset_email
    token = password_resets.create!
    UserMailer.password_reset(self, token).deliver
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new

    render :new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      if request.xhr?
        render partial: "layouts/top_bar"
      else
        redirect_to :back, notice: "User Created"
      end
    else
      if request.xhr?
        render partial: "users/signup", locals: { user: @user }, status: 422
      else
        render :new, locals: { user: @user }
      end
    end
  end

  def update
    @user = User.find(params[:id])
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.save
      redirect_to new_session_url, notice: "Password Successfully Changed"
    else
      redirect_to :back, notice: @user.errors.full_messages.to_sentence
    end
  end

  def show
    @user = User.includes(:images).find(params[:id])

    render :show
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_signup.html.erb
<%= user.errors.full_messages.to_sentence if user %>

<%= form_for user, remote: true do |f| %>
  <%= label_tag(:email, "Email:") %>
  <%= f.text_field(:email) %>
  <%= label_tag(:password, "Password:") %>
  <%= f.password_field(:password) %>
  <%= label_tag(:password_confirmation, "Confirm Password:") %>
  <%= f.password_field(:password_confirmation) %><br>

  <%= submit_tag("Log In") %>
<% end %>

app/views/users/new.html.erb
<div class="login-page-solo">
	<h1>Sign Up</h1>

	<%= render 'signup', user: @user %>
</div>

app/views/users/show.html.erb
<header class="user-show-title"><h1><%= @user.email.gsub("@", " [at] ").gsub(".com", " [dot] com") %>'s Images</h1></header>


<ul class="user-image-list group">
  <% @user.images.each do |image| %>
    <li class="user-image-list-item">
      <% if current_user && image.user_id == current_user.id %>
        <div class="user-image-list-buttons-holder">
          <%= button_to "Delete", image_url(image), method: :delete, class: "user-image-list-buttons" %>
          <%= link_to "Edit", edit_image_url(image), class: "user-image-list-buttons" %>
        </div>
      <% end %>
      <a href="<%= image_url(image) %>"><img class="user-image-list-img" src="<%= image.image.url(:thumb) %>"></a>
      <article class="user-image-list-body">
        <h3><%= image.title %></h3>
        <p><%= image.description %></p>
      </article>
    </li>
  <% end %>
</ul>