config/routes.rb
ImgurClone::Application.routes.draw do
  resources :users, only: [:new, :create, :show, :update]
  resource :session, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit]

  resources :images do
    resources :comments, only: [:new, :create]
    member do
      post "upvote"
      post "downvote"
    end
  end

  match "/comments/:id/upvote" => "comments#upvote", as: :upvote_comment
  match "/comments/:id/downvote" => "comments#downvote", as: :downvote_comment

  root to: 'images#index'

end

app/models/image.rb
require 'open-uri'

class Image < ActiveRecord::Base
  belongs_to :user
  attr_accessible :description, :title, :album_ids, :image, :image_url, :user_id
  attr_accessor :image_url

  # searchable do
#     text :title, :description
#   end

  has_many :comments, dependent: :destroy
  has_many :user_image_votes, dependent: :destroy

  before_validation :download_remote_image, if: :image_url_provided?

  has_attached_file :image,
    styles: {
      thumb: "140x140#",
      small: "300x",
      large: "600x"
    },
    url: ":s3_path_url",
    path: ":class/:id.:style.:extension"



  validates :image_remote_url, presence: true, if: :image_url_provided?

  validates_attachment :image, presence: true,
    size: { in: 0..1.megabytes }

  validates_attachment_content_type :image,
    :content_type => /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/,
    :message => 'file type is not allowed (only jpeg/png/gif images)'

  def ensure_authorization_token
    self.authorization_token ||= SecureRandom::urlsafe_base64(16)
  end

  def image_url_provided?
    self.image_url && !self.image_url.blank?
  end

  def download_remote_image
    io = open(URI.parse(self.image_url))
    def io.original_filename
      base_uri.path.split('/').last
    end
    self.image = io
    self.image_remote_url = self.image_url
  rescue # catch url errors with validations instead of exceptions (Errno::ENOENT, OpenURI::HTTPError, etc...)
  end

  def comments_by_parent_id
    comment_hash = { nil => [] }
    comments.includes(:user)
      .select("comments.*, SUM(user_comment_votes.vote) AS votes")
      .joins("LEFT OUTER JOIN user_comment_votes ON user_comment_votes.comment_id = comments.id")
      .group("comments.id")
      .each do |comment|
      comment_hash[comment.parent_comment_id] ||= []
      comment_hash[comment.id] ||= []
      comment_hash[comment.parent_comment_id] << comment
    end


    comment_hash.each do |key, comment_array|
      comment_hash[key] =
        comment_array.sort_by do |comment|
          [-comment.votes.to_i, comment.created_at]
        end
    end

    comment_hash
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :ensure_authorization, only: [:edit, :update, :destroy]
  before_filter :require_logged_in!, only: [:upvote, :downvote]

  def new
    @image = Image.new

    render :new
  end

  def create
    params[:image] = { "image"=>params[:image] } if params[:dropped]
    @image = Image.new(params[:image])
    if current_user
      @image.user_id = current_user.id
    else
      @image.ensure_authorization_token
    end

    if @image.save
      respond_to do |format|
        format.html do
          redirect_to edit_image_url(@image, authorization_token: @image.authorization_token), notice: "Image uploaded Successfully"
        end
        format.json { render json: @image.to_json }
      end
    else
      render :new
    end
  end

  def index
    @user = User.new(email: params[:email], password: params[:password])
    page_number = params[:page] || 1
    @images = Image.select("images.*, COALESCE(SUM(user_image_votes.vote), 0) AS votes")
      .joins("LEFT OUTER JOIN user_image_votes ON user_image_votes.image_id = images.id")
      .group("images.id")
      .order("votes DESC, images.created_at DESC")
      .page(page_number)
      .per((request.xhr? ? 24 : 25))
      .padding((request.xhr? ? 1 : 0))

    if current_user
      @recent_images = current_user.images.order("created_at desc").limit(5)
      @title = "Your Recent Images"
    else
      @recent_images = Image.order("created_at desc").limit(5)
      @title = "Most Recent Images"
    end
    
    expires_now
    
    if request.xhr?
      # render json: @images
      render partial: "image_items", locals: { images: @images}, status: 200
    else
      render :index
    end
  end

  def show
    @image = Image.includes(:comments)
      .select("images.*, SUM(user_image_votes.vote) AS votes")
      .joins("LEFT OUTER JOIN user_image_votes ON user_image_votes.image_id = images.id")
      .group("images.id")
      .where("images.id = #{params[:id]}")
      .first
    @comments_by_parent_id = @image.comments_by_parent_id

    if request.xhr?
      render :show, layout: false
    else
      render :show
    end
  end

  def edit
    @image = current_image
    @token = params[:authorization_token]

    render :edit
  end

  def update
    @image = current_image

    if @image.update_attributes(params[:image])
      redirect_to image_url(@image), notice: "Image successfully edited."
    else
      render :edit
    end
  end

  def destroy
    @image = current_image

    if @image.destroy
      if request.referer =~ /user/
        redirect_to :back, notice: "Image Successfully Deleted"
      else
        redirect_to :root, notice: "Image Successfully Deleted"
      end
    else
      redirect_to :back, notice: "Something went wrong."
    end
  end

  def upvote
    handle_vote(1)
  end

  def downvote
    handle_vote(-1)
  end

  private

  def handle_vote(change)
    image_id = params[:id]
    user_id = current_user.id
    @vote = UserImageVote.find_by_user_id_and_image_id(user_id, image_id)
    if @vote
      @vote.vote = (@vote.vote == change ? 0 : change)
    else
      @vote = UserImageVote.new(user_id: user_id, image_id: image_id, vote: change)
    end

    if @vote.save
      if request.xhr?
        render partial: "images/vote_box",
          locals: { up_url: upvote_image_url(id: @vote.image_id),
            down_url: downvote_image_url(id: @vote.image_id),
            votes: UserImageVote.where("image_id = #{@vote.image_id}").sum("vote"),
            model: Image.find(@vote.image_id) }
      else
        redirect_to :back, notice: "Voted Successfully"
      end
    else
      redirect_to :back, notice: "Vote Failed"
    end
  end

  def current_image
    @current_image ||= Image.find(params[:id])
  end

  def ensure_authorization
    unless (current_user && current_user.id == current_image.user_id) ||
          params[:authorization_token] == current_image.authorization_token
      redirect_to :root, notice: "You do not have permission."
    end
  end
end

app/helpers/images_helper.rb
module ImagesHelper
  def get_title(title)
    if title && title.length > 16
      return title[0..15] + "..."
    elsif title
      return title
    else
      return "Untitled Image"
    end
  end
end

app/views/images/_comment.html.erb
<%= render "comments/comment_body", image_id: image_id, comment: comment %>
<ul>
  <% comments_by_parent_id[comment.id].each do |comment| %>
    <li>
      <%= render "comment", image_id: image_id, comment: comment, comments_by_parent_id: comments_by_parent_id %>
    </li>
  <% end %>
</ul>

app/views/images/_comment_form.html.erb
<form action="<%= image_comments_url(image_id: image_id) %>" method="post" class="comment-form" data-remote="true">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <textarea name="comment[body]"></textarea>

  <input type="hidden" name="comment[parent_comment_id]" value="<%= parent_comment_id %>">

  <input type="submit" value="Post">

</form>

app/views/images/_featured_image.html.erb
<div class="featured-image">
	<div class="featured-tag">Featured Image</div>
	<div class="left">
	<%= link_to image_tag((image.image_content_type == "image/gif" ? image.image.url : image.image.url(:small))), image_url(image), remote: true %>
	<div class="hover-vote"><%= render "vote_box", model: image, up_url: upvote_image_url(image), down_url: downvote_image_url(image), votes: image.votes %></div>
	</div>
	<div class="right">
		<h2><%= image.title || "Untitled Image" %></h2>
		<p><%= image.description || "This image schould probably have a description if it's going to be our featured image." %></p>
	</div>
</div>

app/views/images/_image.html.erb
<div class="image-show">

  <% if current_user && image.user_id == current_user.id %>
    <%= button_to "Delete", image_url(image), method: :delete, class: "user-image-buttons" %>
    <%= link_to "Edit", edit_image_url(image), class: "user-image-buttons" %>
  <% end %>

  <h2><%= image.title %></h2>

  <%= link_to image_tag((image.image_content_type == "image/gif" ? image.image.url : image.image.url(:large))), image.image.url %><br>
  <p><%= image.description %></p>

</div>

app/views/images/_image_items.html.erb
<% if images.length == 25 %>
	<%= render "featured_image", image: @images.shift %>
<% end %>

<% images.each do |image| %>
  <li>
    <%= link_to image_tag(image.image.url(:thumb)), image_url(image), class: "image-square", remote: true %>
    <div class="hover-vote"><%= render "vote_box", model: image, up_url: upvote_image_url(image), down_url: downvote_image_url(image), votes: image.votes %></div>
  </li>
<% end %>

<%= paginate images %>

app/views/images/_links.html.erb
<div class="link-box">
  <h3>Link</h3>
  <input type="text" class="link-input" value="<%= image_url(image) %>" readonly="readonly">
  <h3>Direct Link</h3>
  <input type="text" class="link-input" value="<%= image.image.url %>" readonly="readonly">
  <h3>HTML Embed Code</h3>
  <input type="text" class="link-input" value='<a href="<%= image_url(image) %>"><img src="<%= image.image.url %>" alt="<%= image.title %>">' readonly="readonly">
  <% if @token %>
    <h3 class="deletion-link">Deletion Link</h3>
    <input type="text" class="link-input" value="<%= 'fill me in later' %>" readonly="readonly">
  <% end %>
</div>

app/views/images/_recent_images.html.erb
<ul class="sidebar-image-list">
  <h3><%= title %></h3>
<% images.each do |image| %>

  <li class="sidebar-image-list-item">
    <a href="<%= image_url(image) %>" data-remote="true"><img class="sidebar-image-list-img" src="<%= image.image.url(:thumb) %>"></a>
    <article class="sidebar-image-list-body">
      <a href="<%= image_url(image) %>" data-remote="true"><h4><%= get_title(image.title) %></h4></a>
    </article>
  </li>
<% end %>

app/views/images/_upload_box.html.erb
<%= form_for image, url: { action: "create" }, html: { id: 'new-image' } do |f| %>
  <h3>Upload an image:</h3>
  <%= f.file_field :image, class: "file-field" %><br><br>
  <h3>...or paste a URL:</h3>
  <%= f.text_field :image_url %><br><br>

  <%= f.submit "Upload" %>
<% end %>

app/views/images/_vote_box.html.erb
<div class="vote-box">
  <div class="vote-button-holder">
    <%= button_to "+", up_url, method: :post, class: "upvote#{ ' selected' if up_selected(model) }", form_class: "upvote-form", remote: true %>
    <%= button_to "-", down_url, method: :post, class: "downvote#{ ' selected' if down_selected(model) }", form_class: "downvote-form", remote: true %>
  </div>
  <div class="vote-number"><%= votes || 0 %></div>
</div>

app/views/images/edit.html.erb
<%= @image.errors.full_messages.to_sentence %>

<%= render "image", image: @image %>

<%= render "links", image: @image %>


<%= form_for @image, url: { action: "update" }, html: { class: "edit-form"} do |f| %>

  Add a Title(optional):<br>
  <%= f.text_field :title %><br>
  Add a Description(optional):<br>
  <%= f.text_area :description %><br>

  <%= hidden_field_tag(:authorization_token, @token) %>


  <%= f.submit "Save" %>
<% end %>

app/views/images/index.html.erb
<input type="hidden" class="page-num" value="<%= params[:page] || 1 %>">
<input type="hidden" class="total-pages" value="<%= @images.total_pages %>"></input>

<ul class="image-list">
  <%= render "image_items", images: @images %>
</ul>

<section class="sidebar group">
  <%= render 'upload_box', image: Image.new %>

  <%= render 'recent_images', images: @recent_images, title: @title %>
</section>

app/views/images/new.html.erb
<%= @image.errors.full_messages.to_sentence %>

<%= form_for @image, url: { action: "create" }, html: { id: 'new-image-centered' } do |f| %>
  <h3>Upload an image:</h3>
  <%= f.file_field :image, class: "file-field" %><br><br>
  <h3>...or paste a URL:</h3>
  <%= f.text_field :image_url %><br><br>

  <%= f.submit "Upload" %>
<% end %>

app/views/images/show.html.erb
<%= render "image", image: @image %>

<%= render "links", image: @image %>

<%= render "images/vote_box", up_url: upvote_image_url(@image), down_url: downvote_image_url(@image), votes: @image.votes, model: @image %>

<%= render "comment_form", parent_comment_id: nil, image_id: @image.id %>

<ul class="comment-list">
  <% @comments_by_parent_id[nil].each do |comment| %>
    <li>
      <%= render "comment", image_id: @image.id, comment: comment, comments_by_parent_id: @comments_by_parent_id %>
    </li>
  <% end %>
</ul>