config/routes.rb
ImgurClone::Application.routes.draw do
  resources :users, only: [:new, :create, :show, :update]
  resource :session, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit]

  resources :images do
    resources :comments, only: [:new, :create]
    member do
      post "upvote"
      post "downvote"
    end
  end

  match "/comments/:id/upvote" => "comments#upvote", as: :upvote_comment
  match "/comments/:id/downvote" => "comments#downvote", as: :downvote_comment

  root to: 'images#index'

end

app/views/layouts/_top_bar.html.erb
<nav class="top-bar">

  <ul class="top-left">
    <li><%= link_to "imgDropper", root_url %></li>
    <li><%= link_to "Upload an Image", new_image_url %></li>
  </ul>
  <ul class="top-right">
    <% if current_user %>
      <li><%= link_to "Log out", session_url, method: :delete, class: "logout" %></li>
      <li class="user-button">
        <%= link_to current_user.email, user_url(current_user) %>
      </li>
    <% else %>
      <li class="login-button">
        <%= link_to "Log In", new_session_url %>
      </li>
      <li class="signup-button">
        <%= link_to "Sign Up", new_user_url %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>imgDropper</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="body">

  <div class="login-overlay">
    <div class="transparent-background login"></div>
    <div class="signup-page">
      <%= render "users/signup", user: User.new unless current_user %>
    </div>
    <div class="login-page">
      <%= render "sessions/login" unless current_user %>
    </div>
  </div>

  <div class="show-page-holder">
    <div class="transparent-background show"></div>
    <div class="nested-scroll-fix">
      <div class="nested-show-page"></div>
    </div>
  </div>

  <div class='droppable'><div><p>Drop file anywhere to upload.</p></div></div>
  <div id='dropmask'></div>

  <%= render "layouts/top_bar", current_user: current_user %>

  <div class="flash-notice"><p><%= flash.notice %></p></div>

  <div class="content group">
    <%= yield %>
  </div>
	
	<div id="ajax-loader">
	  <%= image_tag "ajax-loader.gif" %> <br>
	  Loading more posts...
	</div>

</body>
</html>